--- #Tradebot webui playbook
- hosts: azure
  remote_user: azureuser
  become: true
  become_method: sudo
  connection: ssh

  vars_files:
    - key_vars.yml
    - ansible_vars.yml

  tasks:
  - name: Get artifact from S3
    get_url:
      url: "{{ artifact_url }}/{{ artifact_name }}"
      dest: "/tmp/{{ artifact_name }}"


  - name: Trigger java process
    shell: "(java -jar /tmp/{{ artifact_name }} > /tmp/tradebotui.out.txt 2>&1 &)"
    async: 10
    poll: 0
    environment:
      AWS_ACCESS_KEY: "{{ access_key }}"
      AWS_SECRET_KEY: "{{ secret_key }}"
      TRADEBOT_SQS_QUEUE_NAME: "{{ TRADEBOT_SQS_QUEUE_NAME }}"
      TRADEBOT_SERVER_REGION: "{{ TRADEBOT_SERVER_REGION }}"
